services:
frontend:
      build: ./kanban-ui
      ports:
        - "4200:80"
      network:
      - app-network
backend:
      build: ./kanban-app
      ports:
        -  "8080:8080"
      environment:
        - POSTGRES_DB: kanban
        - POSTGRES_USER: kanban
        - POSTGRES_PASSWORD: kanban
          network:
            - app-network
kanban-postgres:
    image: "postgres:9.6-alpine"
    container_name: kanban-postgres
    volumes:
      - kanban-data: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB: kanban
      - POSTGRES_USER: kanban
      - POSTGRES_PASSWORD: kanban
        network:
          - app-network

