version: "3.8"

services:
  kanban-ui:
    build: ./kanban-ui
    container_name: kanban-ui
    ports:
      - 4200:80
    networks:
      - app-network
    depends_on:
      - backend

  kanban-app:
    container_name: kanban-app
    build: ./kanban-app
    ports:
      - 8080:8080
    environment:
      DB_SERVER: kanban-postgres
      POSTGRES_DB: kanban
      POSTGRES_USER: kanban
      POSTGRES_PASSWORD: kanban
    networks:
      - app-network
    depends_on:
      - kanban

  kanban-postgres:
    image: "postgres:9.6-alpine"
    container_name: kanban-postgres
    volumes:
      - kanban-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: kanban
      POSTGRES_USER: kanban
      POSTGRES_PASSWORD: kanban
    networks:
      - app-network

networks:
  app-network:

volumes:
  kanban-data:
