services:
  frontend:
    build:
      context: ./kanban-ui
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
backend:
  app:
    build:
      context: ./kanban-app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

    environment:
        - POSTGRES_DB: kanban
        - POSTGRES_USER: kanban
        - POSTGRES_PASSWORD: kanban
          network:
            - app-network
kanban-postgres:
    image: "postgres:9.6-alpine"
    container_name: kanban-postgres
    volumes:
      - kanban-data: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB: kanban
      - POSTGRES_USER: kanban
      - POSTGRES_PASSWORD: kanban
        network:
          - app-network

