version: "3.8"

services:
  frontend:
    build:
      context: ./kanban-ui
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    networks:
      - app-network

  backend:
    container_name: kanban-app  # Ensures proper name resolution
    build:
      context: ./kanban-app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      POSTGRES_DB: kanban
      POSTGRES_USER: kanban
      POSTGRES_PASSWORD: kanban
    networks:
      - app-network

  db:
    image: "postgres:9.6-alpine"
    container_name: kanban-postgres
    volumes:
      - kanban-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: kanban
      POSTGRES_USER: kanban
      POSTGRES_PASSWORD: kanban
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: kanban-nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend  # Ensures backend starts first
    networks:
      - app-network

networks:
  app-network:

volumes:
  kanban-data:
