apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanban-ui
  labels:
    app: kanban-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kanban-ui
  template:
    metadata:
      labels:
        app: kanban-ui
    spec:
      containers:
        - name: kanban-ui
          image: nandini965/kanban-ui:latest
          ports:
            - containerPort: 4200

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanban-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kanban-app
  template:
    metadata:
      labels:
        app: kanban-app
    spec:
      containers:
        - name: kanban-app
          image: nandini965/kanban-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_SERVER
              value: "kanban-postgres"
            - name: POSTGRES_DB
              value: "kanban"
            - name: POSTGRES_USER
              value: "kanban"
            - name: POSTGRES_PASSWORD
              value: "kanban"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanban-postgres
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kanban-postgres
  template:
    metadata:
      labels:
        app: kanban-postgres
    spec:
      containers:
        - name: kanban-postgres
          image: postgres:9.6-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "kanban"
            - name: POSTGRES_USER
              value: "kanban"
            - name: POSTGRES_PASSWORD
              value: "kanban"