apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanban-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kanban-postgres
  template:
    metadata:
      labels:
        app: kanban-postgres
    spec:
      containers:
        - name: kanban-postgres
          image: postgres:9.6-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "kanban"]
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "kanban"]
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanban-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kanban-app
  template:
    metadata:
      labels:
        app: kanban-app
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'until nc -zv kanban-postgres 5432; do echo "Waiting for Postgres..."; sleep 2; done']
      containers:
        - name: kanban-app
          image: nandini965/kanban-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_SERVER
              value: "kanban-postgres.default.svc.cluster.local"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanban-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kanban-ui
  template:
    metadata:
      labels:
        app: kanban-ui
    spec:
      initContainers:
        - name: wait-for-app
          image: busybox
          command: ['sh', '-c', 'until nc -zv kanban-app 8080; do echo "Waiting for Backend..."; sleep 2; done']
      containers:
        - name: kanban-ui
          image: nandini965/kanban-ui:latest
          ports:
            - containerPort: 80
