apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanban-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kanban-postgres
  template:
    metadata:
      labels:
        app: kanban-postgres
    spec:
      restartPolicy: Always  # Ensures the pod restarts on failure
      containers:
        - name: kanban-postgres
          image: postgres:9.6-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: kanban
            - name: POSTGRES_USER
              value: kanban
            - name: POSTGRES_PASSWORD
              value: kanban

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanban-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kanban-app
  template:
    metadata:
      labels:
        app: kanban-app
    spec:
      containers:
        - name: kanban-app
          image: nandini965/kanban-app:latest
          env:
            - name: DB_SERVER
              value: "kanban-postgres.default.svc.cluster.local"
            - name: POSTGRES_DB
              value: "kanban"
            - name: POSTGRES_USER
              value: "kanban"
            - name: POSTGRES_PASSWORD
              value: "kanban"
          ports:
            - containerPort: 8080
              protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanban-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kanban-ui
  template:
    metadata:
      labels:
        app: kanban-ui
    spec:
      containers:
        - name: kanban-ui
          image: nandini965/kanban-ui:latest
          ports:
            - containerPort: 80
          env:
            - name: KANBAN_APP_API_URL
              value: "kanban-app.default.svc.cluster.local"
