
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kanban-board-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx  # Add this line
  rules:
    - host: kanban.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kanban-ui
                port:
                  number: 80
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: kanban-app
                port:
                  number: 8080
