# kanban-ui Service
apiVersion: v1
kind: Service
metadata:
  name: kanban-ui
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31978  # Optional: Define a fixed NodePort
  selector:
    app: kanban-ui

---

apiVersion: v1
kind: Service
metadata:
  name: kanban-postgres
spec:
  selector:
    app: kanban-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432