apiVersion: v1
kind: Service
metadata:
  name: kanban-ui
spec:
  type: NodePort
  ports:
    - port: 4200
      targetPort: 4200

  selector:
    app: kanban-ui

---
apiVersion: v1
kind: Service
metadata:
  name: kanban-app
spec:
  selector:
    app: kanban-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: kanban-postgres
spec:
  selector:
    app: kanban-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432