# kanban-ui Service
apiVersion: v1
kind: Service
metadata:
  name: kanban-ui-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
     # nodePort: 30080 # Optional: Define a fixed NodePort
  selector:
    app: kanban-ui
---
apiVersion: v1
kind: Service
metadata:
  name: kanban-app-service
spec:
  selector:
    app: kanban-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: kanban-postgres-service
spec:
  selector:
    app: kanban-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432