apiVersion: v1
kind: Service
metadata:
  name: kanban-ui
  labels:
    group: backend
spec:
  type: LoadBalancer
  selector:
    app: kanban-ui
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kanban-app
  labels:
    group: backend
spec:
  type: ClusterIP
  selector:
    app: kanban-app
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    group: db
spec:
  type: ClusterIP
  selector:               # indicates into which pods ClusterIP provides access
    app: postgres
  ports:
    - port: 5432          # port exposed outside ClusterIP
      targetPort: 5432